### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by baxyz** [a-dekker/BarWal#18]
As far as I saw, it misses three strings to translate (during the 5 sec of cancelation):

- https://github.com/a-dekker/BarWal/blob/4c5bfc355b42bfc86c0dab0a4bb77232f746c366/qml/pages/MainPage.qml#L94
- https://github.com/a-dekker/BarWal/blob/4c5bfc355b42bfc86c0dab0a4bb77232f746c366/qml/pages/MainPage.qml#L104
- https://github.com/a-dekker/BarWal/blob/274760555498de63a176c6a9be7ab2c2e060a81b/qml/pages/BarcodesPage.qml#L186

Of course, this is very minor.

**Comment by a-dekker** [comment]
See https://github.com/a-dekker/BarWal/commit/340471543b697bf68459bab9c6ac40c051ab18b8
